2017-01-24 11:03:37,046 ERROR 1963 [-/127.0.0.1/-/12ms GET /list] nodejs.Error: template not found: news/list.tpl
    at createTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:207:31)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:210:13)
    at handle (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:253:25)
    at /Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:264:21
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:243:17)
    at new_cls.render (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:305:14)
    at Promise (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:12:27)
    at View.render (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:11:12)

pid: 1963
hostname: hankeweideMacBook-Pro.local

2017-01-24 11:04:27,019 ERROR 1968 [-/127.0.0.1/-/14ms GET /list] nodejs.Error: template not found: new/list.tpl
    at createTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:207:31)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:210:13)
    at handle (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:253:25)
    at /Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:264:21
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:243:17)
    at new_cls.render (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:305:14)
    at Promise (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:12:27)
    at View.render (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:11:12)

pid: 1968
hostname: hankeweideMacBook-Pro.local

2017-01-24 11:05:08,168 ERROR 1971 [-/127.0.0.1/-/15ms GET /list] nodejs.Error: template not found: list.tpl
    at createTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:207:31)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:210:13)
    at handle (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:253:25)
    at /Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:264:21
    at next (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:243:17)
    at new_cls.render (/Users/hankewei/Desktop/Node/node/node_modules/nunjucks/src/environment.js:305:14)
    at Promise (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:12:27)
    at View.render (/Users/hankewei/Desktop/Node/node/node_modules/egg-view-nunjucks/lib/view.js:11:12)

pid: 1971
hostname: hankeweideMacBook-Pro.local

2017-01-24 12:29:05,274 ERROR 2101 [-/127.0.0.1/-/13ms GET /find] nodejs.TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:118:63)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:118:63)

pid: 2101
hostname: hankeweideMacBook-Pro.local

2017-01-24 12:35:44,480 ERROR 2111 [-/127.0.0.1/-/10ms GET /find] nodejs.TypeError: Cannot read property 'get' of undefined
    at User.find (/Users/hankewei/Desktop/Node/node/app/service/user.js:9:20)
    at next (native)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:65:19)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:118:63)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)

pid: 2111
hostname: hankeweideMacBook-Pro.local

2017-01-24 12:39:35,435 ERROR 2119 [-/127.0.0.1/-/10ms GET /find] nodejs.TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:118:63)
    at next (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/node/node_modules/co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/node/node_modules/co/index.js:118:63)

pid: 2119
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:53:51,895 ERROR 2516 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2516)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2516
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:53:51,899 ERROR 2515 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2515)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2515
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:53:51,955 ERROR 2513 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2513)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2513
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:53:51,974 ERROR 2514 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2514)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2514
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:05,785 ERROR 2520 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2520)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2520
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:05,881 ERROR 2522 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2522)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2522
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:05,914 ERROR 2523 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2523)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2523
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:05,922 ERROR 2521 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2521)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2521
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:39,950 ERROR 2537 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2537)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2537
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:40,007 ERROR 2536 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2536)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2536
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:40,032 ERROR 2534 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2534)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2534
hostname: hankeweideMacBook-Pro.local

2017-01-24 14:54:40,078 ERROR 2535 nodejs.EACCESError: bind EACCES null:80 (uncaughtException throw 1 times on pid:2535)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at cb (net.js:1324:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
code: 'EACCES'
errno: 'EACCES'
syscall: 'bind'
address: null
port: 80
name: 'EACCESError'
pid: 2535
hostname: hankeweideMacBook-Pro.local

2017-01-26 16:11:24,597 ERROR 4474 [-/127.0.0.1/-/85ms GET /find.html] nodejs.ReferenceError: conosle is not defined
    at Object.find (/Users/hankewei/Desktop/Node/yunnode/node/app/controller/find.js:6:4)
    at next (native)
    at Object.dispatch (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
    at next (native)
    at onFulfilled (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

pid: 4474
hostname: hankeweideMacBook-Pro.local

2017-01-26 16:11:50,282 ERROR 4474 [-/127.0.0.1/-/74ms GET /find.html] nodejs.ReferenceError: conosle is not defined
    at Object.find (/Users/hankewei/Desktop/Node/yunnode/node/app/controller/find.js:6:4)
    at next (native)
    at Object.dispatch (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
    at next (native)
    at onFulfilled (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

pid: 4474
hostname: hankeweideMacBook-Pro.local

2017-01-26 16:11:58,508 ERROR 4474 [-/127.0.0.1/-/75ms GET /find.html] nodejs.ReferenceError: conosle is not defined
    at Object.find (/Users/hankewei/Desktop/Node/yunnode/node/app/controller/find.js:6:4)
    at next (native)
    at Object.dispatch (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.5.4.0@koa-router/lib/router.js:336:14)
    at next (native)
    at onFulfilled (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

pid: 4474
hostname: hankeweideMacBook-Pro.local

2017-02-03 10:45:59,832 ERROR 1086 [-/127.0.0.1/-/22298ms GET /find.html] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:160:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake._onTimeout (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:127:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at Object.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.6.1@ali-rds/lib/client.js:28:10)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:136:8
    at Object.thunkToPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:135:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:99:29)
    sql: SELECT * FROM `users` WHERE `user_id` = 1 LIMIT 0, 1
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1086
hostname: hankeweideMacBook-Pro.local

2017-02-03 11:00:35,346 ERROR 1530 [-/127.0.0.1/-/20619ms GET /loginAction?userName=hkw&userPassword=12345] nodejs.ER_WRONG_TABLE_NAMEError: ER_WRONG_TABLE_NAME: Incorrect table name ''
    at Query.Sequence._packetToError (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:199:23)
    at Object.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.6.1@ali-rds/lib/client.js:28:10)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:136:8
    at Object.thunkToPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:135:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:118:63)
    sql: SELECT * FROM `` WHERE `user_name` = 'hkw' AND `user_password` = '12345' LIMIT 0, 1
code: 'ER_WRONG_TABLE_NAME'
errno: 1103
sqlState: '42000'
index: 0
name: 'ER_WRONG_TABLE_NAMEError'
pid: 1530
hostname: hankeweideMacBook-Pro.local

2017-02-03 11:13:49,518 ERROR 1892 [-/127.0.0.1/-/71ms GET /createUser?userName=hkw2&userPassword=123456] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'user_id' doesn't have a default value
    at Query.Sequence._packetToError (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:199:23)
    at Object.<anonymous> (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.6.1@ali-rds/lib/client.js:28:10)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:136:8
    at Object.thunkToPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:135:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:99:29)
    at onFulfilled (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:69:7)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:54:5
    at Object.co (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:50:10)
    at Object.toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:118:63)
    sql: INSERT INTO `users`(`user_name`, `user_password`) VALUES('hkw2', '123456')
code: 'ER_NO_DEFAULT_FOR_FIELD'
errno: 1364
sqlState: 'HY000'
index: 0
name: 'ER_NO_DEFAULT_FOR_FIELDError'
pid: 1892
hostname: hankeweideMacBook-Pro.local

2017-02-03 13:22:51,829 ERROR 3401 nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND hankewei.xyz hankewei.xyz:3306 (hankewei.xyz)
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    --------------------
    at Protocol._enqueue (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.6.1@ali-rds/lib/client.js:28:10
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:136:8
    at thunkToPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:135:10)
    at toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:99:29)
    sql: select now() as currentTime;
code: 'ENOTFOUND'
errno: 'ENOTFOUND'
syscall: 'getaddrinfo'
hostname: 'hankewei.xyz'
host: 'hankewei.xyz'
port: '3306'
fatal: true
name: 'ENOTFOUNDError'
pid: 3401
hostname: hankeweideMacBook-Pro.local

2017-02-03 13:22:51,833 ERROR 3401 [-/127.0.0.1/-/0ms GET /] nodejs.ENOTFOUNDError: getaddrinfo ENOTFOUND hankewei.xyz hankewei.xyz:3306 (hankewei.xyz) (hankewei.xyz) (hankewei.xyz)
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    --------------------
    at Protocol._enqueue (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.13.0@mysql/lib/Pool.js:202:8)
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.2.6.1@ali-rds/lib/client.js:28:10
    at /Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:136:8
    at thunkToPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:135:10)
    at toPromise (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:119:55)
    at next (/Users/hankewei/Desktop/Node/yunnode/node/node_modules/.4.6.0@co/index.js:99:29)
    sql: select now() as currentTime;
code: 'ENOTFOUND'
errno: 'ENOTFOUND'
syscall: 'getaddrinfo'
hostname: 'hankewei.xyz'
host: 'hankewei.xyz'
port: '3306'
fatal: true
name: 'ENOTFOUNDError'
pid: 3401
hostname: hankeweideMacBook-Pro.local

